vim.o.path = vim.o.path..'**'
vim.o.swapfile = false
vim.o.undofile = true
vim.o.termguicolors = true
vim.o.lazyredraw = true
vim.o.gdefault = true
vim.o.linebreak = true
vim.o.showbreak = string.rep(' ', 3)
vim.o.breakindent = true
vim.o.breakindentopt = 'sbr'
vim.o.mouse = 'a'
if vim.fn.executable("rg") then
  vim.o.grepprg = "rg --vimgrep --no-heading"
  vim.o.grepformat = "%f:%l:%c:%m"
end
vim.o.incsearch = true
vim.o.completeopt = 'menuone,noinsert,noselect'
vim.o.shortmess = vim.o.shortmess .. 'aoOtTIc'
vim.o.showmode = false
vim.o.sidescrolloff = 5
vim.o.sidescroll = 1
vim.o.splitbelow = true
vim.o.splitright = true
vim.o.smarttab = true
vim.o.tabstop = 2
vim.o.shiftwidth = 2
vim.o.softtabstop = -1
vim.o.shiftround = true
vim.o.expandtab = true
vim.o.smartindent = true
vim.o.confirm = true
vim.o.inccommand = 'nosplit'
vim.o.omnifunc = 'syntaxcomplete#Complete'
vim.o.completefunc =' syntaxcomplete#Complete'
vim.o.pumheight = 10
vim.o.updatetime = 50
vim.o.ttimeoutlen = 0
vim.o.wildcharm = 9
vim.o.wildignorecase = true
vim.o.wildignore = '*/node_modules/*,*.git/*,*/bower_components/*'
vim.o.diffopt = 'context:3,algorithm:patience,indent-heuristic,iwhite'
vim.wo.list = true
vim.o.listchars = 'tab:┊ ,trail:•,extends:»,precedes:«,nbsp:⣿'
vim.wo.number = true
vim.wo.wrap = false
vim.o.tabline = "%!functions#tabline()"
